### PR TITLE
Deploy Kubernetes dashboard in local-setup

### PR DESCRIPTION
**Pull request by sergioifg94**
## Description

Add resources and automation to deploy the Kubernetes dashboard in local-setup

## Verification steps

1. Run the local-setup
    ```sh
    make local-setup
    ```
2. Verify the dashboard is deployed and follow the instructions to access it
3. Verify that the instructions are correct and the dashboard is accessible

### CODE REVIEW

**Comment by maleck13** [comment]
getting an error with local-setup

```
eploying Kubernetes Dashboard to (mctc-control-plane)
Switched to context "kind-mctc-control-plane".
namespace/kubernetes-dashboard created
serviceaccount/kubernetes-dashboard created
service/kubernetes-dashboard created
secret/kubernetes-dashboard-certs created
secret/kubernetes-dashboard-csrf created
secret/kubernetes-dashboard-key-holder created
configmap/kubernetes-dashboard-settings created
role.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrole.rbac.authorization.k8s.io/kubernetes-dashboard created
rolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
clusterrolebinding.rbac.authorization.k8s.io/kubernetes-dashboard created
deployment.apps/kubernetes-dashboard created
service/dashboard-metrics-scraper created
deployment.apps/dashboard-metrics-scraper created
serviceaccount/admin-user created
clusterrolebinding.rbac.authorization.k8s.io/admin-user created
Error: must specify one of -f and -k
```

**Review by maleck13 — COMMENTED** [review]
failed local-setup for me see above error

**Comment by sergioifg94** [comment]
@maleck13  Looks like it's failing when creating a token to access the dashboard. What version of `kubectl` are you on? I think that the `create token` command was added relatively recently so that might be the reason

**Comment by maleck13** [comment]
1.23.3

**Comment by david-martin** [comment]
@sergioifg94 same here. 1.22.0

What about falling back to the previous instructions for getting the token? https://github.com/kubernetes/dashboard/commit/f78bd53d7561eb614308b1aff5a134668244f2a4
Looks like they should be forwards compatible

**Comment by sergioifg94** [comment]
Thanks @maleck13 @david-martin I followed a similar approach as the one you mentioned above. Should work now

**Review by david-martin — APPROVED** [review]
Works as expected.
Thanks @sergioifg94

**Pull request merged**
